=== gkttk/xml_parser/src/test/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:ts="tariff.schema"
        targetNamespace="tariff.schema"
        elementFormDefault="qualified">

    <element name="tariffs" type="ts:tariffs-type"/>


    <!-- complex types -->
    <complexType name="tariffs-type">
        <sequence>
            <element name="internet-tariff" type="ts:internet-tariff-type" minOccurs="0" maxOccurs="3"/>
            <element name="speak-tariff" type="ts:speak-tariff-type" minOccurs="0" maxOccurs="3"/>
        </sequence>
    </complexType>

    <complexType name="tariff-type" abstract="true">
        <sequence>
            <element name="tariff-name" type="ts:tariff-name-type"/>
            <element name="operator-name" type="ts:operator-name-type"/>
            <element name="payroll" type="ts:decimal-price-type"/>
            <element name="sms-price" type="ts:decimal-price-type"/>
            <element name="call-price" type="ts:call-price-type"/>
        </sequence>
        <attribute name="tariff-id" type="ts:tariff-id-type" use="required"/>
    </complexType>

    <complexType name="internet-tariff-type">
        <complexContent>
            <extension base="ts:tariff-type">
                <sequence>
                    <element name="free-internet-mb" type="positiveInteger" default="300"/>
                    <element name="free-social-media" type="ts:free-social-media-type" minOccurs="0" maxOccurs="3"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="speak-tariff-type">
        <complexContent>
            <extension base="ts:tariff-type">
                <sequence>
                    <element name="free-minutes-abroad" type="positiveInteger" default="150"/>
                    <element name="favourite-number" type="ts:phone-number-type" minOccurs="0" maxOccurs="5"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="call-price-type">
        <sequence>
            <element name="internal-calls" type="ts:decimal-price-type"/>
            <element name="external-calls" type="ts:decimal-price-type"/>
            <element name="landline-calls" type="ts:decimal-price-type"/>
        </sequence>
    </complexType>

    <!--simple types -->

    <simpleType name="tariff-id-type">
        <restriction base="ID">
            <pattern value="[S|I][\d]{5}"/>
        </restriction>
    </simpleType>

    <simpleType name="phone-number-type">
        <restriction base="string">
            <minLength value="9"/>
            <maxLength value="12"/>
            <pattern value="([\d]{3})?[\d]{9}"/>
        </restriction>
    </simpleType>

    <simpleType name="free-social-media-type">
        <restriction base="string">
            <enumeration value="vk"/>
            <enumeration value="instagram"/>
            <enumeration value="twitter"/>
        </restriction>
    </simpleType>

    <simpleType name="tariff-name-type">
        <restriction base="string">
            <minLength value="3"/>
            <maxLength value="14"/>
        </restriction>
    </simpleType>


    <simpleType name="operator-name-type">
        <restriction base="string">
            <enumeration value="mts"/>
            <enumeration value="velcom"/>
            <enumeration value="life"/>
        </restriction>
    </simpleType>

    <simpleType name="decimal-price-type">
        <restriction base="decimal">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

</schema>

=== gkttk/xml_parser/src/test/resources/correct.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns="tariff.schema"
         xmlns:def="http://www.w3.org/2001/XMLSchema-instance"
         def:schemaLocation="tariff.schema schema.xsd">

    <internet-tariff tariff-id="I10001">
        <tariff-name>InternetFirst</tariff-name>
        <operator-name>velcom</operator-name>
        <payroll>25</payroll>
        <sms-price>0.2</sms-price>
        <call-price>
            <internal-calls>0.3</internal-calls>
            <external-calls>0.8</external-calls>
            <landline-calls>1.5</landline-calls>
        </call-price>
        <free-internet-mb>300</free-internet-mb>
        <free-social-media>vk</free-social-media>
        <free-social-media>instagram</free-social-media>
    </internet-tariff>

    <internet-tariff tariff-id="I10002">
        <tariff-name>InternetSecond</tariff-name>
        <operator-name>life</operator-name>
        <payroll>15</payroll>
        <sms-price>0.5</sms-price>
        <call-price>
            <internal-calls>0.5</internal-calls>
            <external-calls>1.5</external-calls>
            <landline-calls>2.5</landline-calls>
        </call-price>
        <free-internet-mb>300</free-internet-mb>
            <free-social-media>twitter</free-social-media>
    </internet-tariff>

    <speak-tariff tariff-id="S10001">
        <tariff-name>SpeakFirst</tariff-name>
        <operator-name>mts</operator-name>
        <payroll>30</payroll>
        <sms-price>0.1</sms-price>
        <call-price>
            <internal-calls>0.1</internal-calls>
            <external-calls>0.3</external-calls>
            <landline-calls>1</landline-calls>
        </call-price>
        <free-minutes-abroad>150</free-minutes-abroad>
        <favourite-number>375291012908</favourite-number>
        <favourite-number>291122341</favourite-number>
        <favourite-number>375444563210</favourite-number>
    </speak-tariff>

    <speak-tariff tariff-id="S10002">
        <tariff-name>SpeakSecond</tariff-name>
        <operator-name>velcom</operator-name>
        <payroll>10</payroll>
        <sms-price>0.2</sms-price>
        <call-price>
            <internal-calls>0.4</internal-calls>
            <external-calls>0.9</external-calls>
            <landline-calls>1</landline-calls>
        </call-price>
        <free-minutes-abroad>150</free-minutes-abroad>
        <favourite-number>375291111111</favourite-number>
    </speak-tariff>


</tariffs>
